### ISSUE TITLE
An error occured [Circular]

### ISSUE THREAD

**Issue by muddaser** [amida-tech/api-boilerplate#2]
I ran the project as per instructions, the server starts on port 4000 and gives this error:

**An error occured [Circular]**

Here's the log if I try to access a route like **/health-check** etc.

```"message":"Not Found","stack":"Error: API not found\n    at APIError.ExtendableError (/home/balderdash/Projects/Blockgen New/central-backend-test/dist/server/helpers/APIError.js:35:15)\n    at new APIError (/home/balderdash/Projects/Blockgen New/central-backend-test/dist/server/helpers/APIError.js:63:105)\n    at /home/balderdash/Projects/Blockgen New/central-backend-test/dist/config/express.js:121:15\n    at Layer.handle [as handle_request] (/home/balderdash/Projects/Blockgen New/central-backend-test/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/balderdash/Projects/Blockgen New/central-backend-test/node_modules/express/lib/router/index.js:312:13)\n    at /home/balderdash/Projects/Blockgen New/central-backend-test/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/home/balderdash/Projects/Blockgen New/central-backend-test/node_modules/express/lib/router/index.js:330:12)\n    at next (/home/balderdash/Projects/Blockgen New/central-backend-test/node_modules/express/lib/router/index.js:271:10)\n    at Layer.handle [as handle_request] (/home/balderdash/Projects/Blockgen New/central-backend-test/node_modules/express/lib/router/layer.js:91:12)\n    at trim_prefix (/home/balderdash/Projects/Blockgen New/central-backend-test/node_modules/express/lib/router/index.js:312:13)\n    at /home/balderdash/Projects/Blockgen New/central-backend-test/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/home/balderdash/Projects/Blockgen New/central-backend-test/node_modules/express/lib/router/index.js:330:12)\n    at next (/home/balderdash/Projects/Blockgen New/central-backend-test/node_modules/express/lib/router/index.js:271:10)\n    at /home/balderdash/Projects/Blockgen New/central-backend-test/node_modules/express-winston/index.js:306:9\n    at Layer.handle [as handle_request] (/home/balderdash/Projects/Blockgen New/central-backend-test/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/balderdash/Projects/Blockgen New/central-backend-test/node_modules/express/lib/router/index.js:312:13)"}```

**Comment by muddaser** [comment]
I tried running the tests with **yarn test**. Got 15 passing.

**Comment by Jehanzeb-Malik** [comment]
Did you find out what was the issue?

**Comment by Akronae** [comment]
Same here

**Comment by unprofessional** [comment]
You may have neglected to use `/api/...` in the path. If I use `/api/health-check` I get back a 200 OK response.

**Comment by Tenemo** [comment]
I'm having a similar issue, I get the [Circular] error during sequelize.sync, routes work okay though.

**Comment by unprofessional** [comment]
We've pushed a host of updates which should fix the [Circular] problem (there should have been a `.catch()` statement for an unresolved promise when initializing sequelize). Likewise, we updated some outdated packages due to security vulnerabilities and have added API versioning in the path (configured in your `.env` -- see the `.env.example`.
